# Generated by Django 5.1.1 on 2024-09-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodectmodel',
            name='description',
        ),
    ]
